#!/bin/bash
# Quick reference for MCP Google Drive Server

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║             MCP GOOGLE DRIVE SERVER - QUICK REFERENCE                ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📡 SERVER: http://192.168.1.114:8547"
echo "🔑 API KEY: 89fbf9d5af4dc97a249de06afb88c7747faa8414af564e8ad4a7d1245bad1adb"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo "SERVICE COMMANDS:"
echo "════════════════════════════════════════════════════════════════════════"
echo "  sudo systemctl start mcp-gdrive      # Start service"
echo "  sudo systemctl stop mcp-gdrive       # Stop service"
echo "  sudo systemctl restart mcp-gdrive    # Restart service"
echo "  sudo systemctl status mcp-gdrive     # Check status"
echo "  sudo journalctl -u mcp-gdrive -f     # Watch logs"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo "TEST COMMANDS:"
echo "════════════════════════════════════════════════════════════════════════"
echo "  # Local test:"
echo "  curl http://localhost:8547/health"
echo ""
echo "  # Network test:"
echo "  curl -H \"X-API-Key: 89fbf9d5af4dc97a249de06afb88c7747faa8414af564e8ad4a7d1245bad1adb\" http://192.168.1.114:8547/health"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
echo "SETUP OAUTH (if not done):"
echo "════════════════════════════════════════════════════════════════════════"
echo "  1. Edit .env:    nano /mnt/merged_ssd/mcp-gdrive/.env"
echo "  2. Add OAuth keys file to: /home/pi/.config/mcp-gdrive/gcp-oauth.keys.json"
echo "  3. Authenticate: npm run start:http (then Ctrl+C after auth)"
echo "  4. Start service: sudo systemctl start mcp-gdrive"
echo ""
echo "════════════════════════════════════════════════════════════════════════"
